// ⚠️  DO NOT EDIT THIS FILE BY HAND.
//
// Regenerate from the live Supabase schema whenever a migration is applied:
//
//   npm run gen:types
//
// Requires Supabase CLI authentication:
//   npx supabase login          (one-time, opens browser)
//   — or —
//   SUPABASE_ACCESS_TOKEN=<token> npm run gen:types
//
// Get a token at: https://supabase.com/dashboard/account/tokens

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      homes: {
        Row: {
          id: string
          name: string
          invite_code: string
          calendar_token: string        // migration 0004
          next_shop_date: string | null // migration 0006 (date as YYYY-MM-DD string)
          created_at: string
        }
        Insert: {
          id?: string
          name?: string
          invite_code?: string
          calendar_token?: string
          next_shop_date?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          invite_code?: string
          calendar_token?: string
          next_shop_date?: string | null
          created_at?: string
        }
        Relationships: []
      }
      home_members: {
        Row: {
          id: string
          home_id: string
          user_id: string
          role: 'owner' | 'member'
          display_name: string | null
          avatar_color: string | null
          joined_at: string
        }
        Insert: {
          id?: string
          home_id: string
          user_id: string
          role?: 'owner' | 'member'
          display_name?: string | null
          avatar_color?: string | null
          joined_at?: string
        }
        Update: {
          id?: string
          home_id?: string
          user_id?: string
          role?: 'owner' | 'member'
          display_name?: string | null
          avatar_color?: string | null
          joined_at?: string
        }
        Relationships: []
      }
      shopping_items: {
        Row: {
          id: string
          home_id: string
          name: string
          quantity: string | null
          category: string | null
          checked: boolean
          added_by: string | null
          checked_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          home_id: string
          name: string
          quantity?: string | null
          category?: string | null
          checked?: boolean
          added_by?: string | null
          checked_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          home_id?: string
          name?: string
          quantity?: string | null
          category?: string | null
          checked?: boolean
          added_by?: string | null
          checked_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      expenses: {
        Row: {
          id: string
          home_id: string
          title: string
          amount: number
          paid_by: string
          split_type: 'equal' | 'custom' | 'solo'
          category: string | null
          is_recurring: boolean
          recurrence_interval: 'weekly' | 'monthly' | 'yearly' | null
          notes: string | null
          date: string
          created_at: string
        }
        Insert: {
          id?: string
          home_id: string
          title: string
          amount: number
          paid_by: string
          split_type?: 'equal' | 'custom' | 'solo'
          category?: string | null
          is_recurring?: boolean
          recurrence_interval?: 'weekly' | 'monthly' | 'yearly' | null
          notes?: string | null
          date?: string
          created_at?: string
        }
        Update: {
          id?: string
          home_id?: string
          title?: string
          amount?: number
          paid_by?: string
          split_type?: 'equal' | 'custom' | 'solo'
          category?: string | null
          is_recurring?: boolean
          recurrence_interval?: 'weekly' | 'monthly' | 'yearly' | null
          notes?: string | null
          date?: string
          created_at?: string
        }
        Relationships: []
      }
      expense_splits: {
        Row: {
          id: string
          expense_id: string
          user_id: string
          amount: number
          settled: boolean
          settled_at: string | null
        }
        Insert: {
          id?: string
          expense_id: string
          user_id: string
          amount: number
          settled?: boolean
          settled_at?: string | null
        }
        Update: {
          id?: string
          expense_id?: string
          user_id?: string
          amount?: number
          settled?: boolean
          settled_at?: string | null
        }
        Relationships: []
      }
      chores: {
        Row: {
          id: string
          home_id: string
          title: string
          description: string | null
          assigned_to: string | null
          frequency: 'once' | 'daily' | 'weekly' | 'fortnightly' | 'monthly' | null
          last_completed_at: string | null
          completed_by: string | null
          due_date: string | null
          created_at: string
        }
        Insert: {
          id?: string
          home_id: string
          title: string
          description?: string | null
          assigned_to?: string | null
          frequency?: 'once' | 'daily' | 'weekly' | 'fortnightly' | 'monthly' | null
          last_completed_at?: string | null
          completed_by?: string | null
          due_date?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          home_id?: string
          title?: string
          description?: string | null
          assigned_to?: string | null
          frequency?: 'once' | 'daily' | 'weekly' | 'fortnightly' | 'monthly' | null
          last_completed_at?: string | null
          completed_by?: string | null
          due_date?: string | null
          created_at?: string
        }
        Relationships: []
      }
      activity_feed: {
        Row: {
          id: string
          home_id: string
          user_id: string | null
          action: string
          entity_type: string
          entity_id: string | null
          metadata: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          home_id: string
          user_id?: string | null
          action: string
          entity_type: string
          entity_id?: string | null
          metadata?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          home_id?: string
          user_id?: string | null
          action?: string
          entity_type?: string
          entity_id?: string | null
          metadata?: Json | null
          created_at?: string
        }
        Relationships: []
      }
      settlements: {
        // migration 0003 — immutable ledger, no update/delete policies
        Row: {
          id: string
          home_id: string
          paid_by: string
          paid_to: string
          amount: number
          note: string | null
          created_at: string
        }
        Insert: {
          id?: string
          home_id: string
          paid_by: string
          paid_to: string
          amount: number
          note?: string | null
          created_at?: string
        }
        Update: {
          // intentionally minimal — settlements are immutable by design
          id?: string
          home_id?: string
          paid_by?: string
          paid_to?: string
          amount?: number
          note?: string | null
          created_at?: string
        }
        Relationships: []
      }
      home_custom_categories: {
        // migration 0008
        Row: {
          id: string
          home_id: string
          name: string
          color: string
          emoji: string
          created_at: string
        }
        Insert: {
          id?: string
          home_id: string
          name: string
          color: string
          emoji: string
          created_at?: string
        }
        Update: {
          id?: string
          home_id?: string
          name?: string
          color?: string
          emoji?: string
          created_at?: string
        }
        Relationships: []
      }
      budgets: {
        // migration 0008
        Row: {
          id: string
          home_id: string
          category: string
          month: string       // 'YYYY-MM-01'
          amount: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          home_id: string
          category: string
          month: string
          amount: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          home_id?: string
          category?: string
          month?: string
          amount?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      notifications: {
        // migration 0007 — written by DB trigger, never by the client
        Row: {
          id: string
          home_id: string
          user_id: string
          actor_id: string | null
          type: string
          title: string
          entity_id: string | null
          read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          home_id: string
          user_id: string
          actor_id?: string | null
          type: string
          title: string
          entity_id?: string | null
          read?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          home_id?: string
          user_id?: string
          actor_id?: string | null
          type?: string
          title?: string
          entity_id?: string | null
          read?: boolean
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: {
      get_user_home_id: {
        Args: Record<string, never>
        Returns: string | null
      }
      get_home_by_invite_code: {
        // migration 0002 — security definer, bypasses RLS for join flow
        Args: { code: string }
        Returns: string | null // uuid
      }
      create_home_for_user: {
        // migration 0010 — SECURITY DEFINER; creates home + owner member atomically
        Args: { home_name?: string; display_name?: string }
        Returns: string // uuid of new home
      }
      join_home_by_invite_code: {
        // migration 0010 — SECURITY DEFINER; looks up invite code + inserts member atomically
        Args: { code: string; display_name?: string }
        Returns: string // uuid of joined home
      }
      settle_up: {
        // migration 0003 — atomically settles splits + records settlement
        Args: {
          p_home_id: string
          p_debtor_id: string
          p_creditor_id: string
          p_amount: number
          p_note?: string | null
        }
        Returns: string // uuid of the new settlement row
      }
      leave_home: {
        // migration 0005 — removes caller from home; deletes home if last member
        Args: Record<string, never>
        Returns: undefined
      }
      delete_account: {
        // migration 0005 — leave_home() then deletes auth.users row
        Args: Record<string, never>
        Returns: undefined
      }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
